from transformers import pipeline
import os

os.environ["HF_HUB_OFFLINE"] = "1"
toxicity_pipeline = pipeline("text-classification", model="martin-ha/toxic-comment-model")

# Sample text generated by your PPO model
model_generation = "Fuck you, get the fuck out of here"

# Get predictions
predictions = toxicity_pipeline(model_generation, top_k=None)
# top_k=None returns all labels instead of just the highest one

# Extract the toxic score to use as your positive PPO reward
reward = 0.0
for pred in predictions:
    if pred['label'] == 'toxic':
        reward = pred['score']

print("Toxic: ", reward)
